name: pg-interval-dependencies
services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -q -d postgres -U postgres"
      timeout: 10s
      interval: 10s
      retries: 3
    expose:
      - "5432"
